version = 1

exclude_patterns = [
    "*.min.js",
    "trumbowyg"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "jquery",
    "mongo"
  ]
